[package]
name = "crontabcheck"
version = "0.5.0"
authors = ["Benoît Faucon <faucon.benoit@cegetel.net>"]

[dependencies]
clap = "2.25"

[dependencies.nom]
version = "3.0"
features = ["verbose-errors"]
